// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Login: typeof import('./src/components/Login.vue')['default']
    Menu: typeof import('./src/components/User/Menu.vue')['default']
    MenuBody: typeof import('./src/components/User/Menu/MenuBody.vue')['default']
    MenuHeader: typeof import('./src/components/User/Menu/MenuHeader.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPagination: typeof import('naive-ui')['NPagination']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpace: typeof import('naive-ui')['NSpace']
    Panel: typeof import('./src/components/User/Panel.vue')['default']
    PanelCategory: typeof import('./src/components/User/panel/PanelCategory/PanelCategory.vue')['default']
    PanelClass: typeof import('./src/components/User/panel/PanelClass/PanelClass.vue')['default']
    PanelHeader: typeof import('./src/components/User/panel/PanelHeader.vue')['default']
    PanelHome: typeof import('./src/components/User/panel/PanelHome/PanelHome.vue')['default']
    PanelMovies: typeof import('./src/components/User/panel/PanelMovies/PanelMovies.vue')['default']
    PanelSource: typeof import('./src/components/User/panel/PanelSource/PanelSource.vue')['default']
    PanelSourceClass: typeof import('./src/components/User/panel/PanelSourceClass/PanelSourceClass.vue')['default']
    PanelSourceMovie: typeof import('./src/components/User/panel/PanelSourceMovie/PanelSourceMovie.vue')['default']
    PanelSystem: typeof import('./src/components/User/panel/PanelSystem/PanelSystem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/User/Setting/Setting.vue')['default']
    User: typeof import('./src/components/User.vue')['default']
  }
}
